#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.1
#  in conjunction with Tcl version 8.6
#    Apr 19, 2020 04:34:51 PM -04  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global spinbox
    spinbox = tk.StringVar()
    global a
    a = tk.StringVar()
    a.set('Mediciones\n\nUĺtima actualización:\t19/04/20 14:32:03\n\n\nTemperatura: 41 °C\n\nPresión: 1.01 atm\n\nCoordenadas: (-21.7399329,-59.9498255)\n\nOrientación: 21,324°')

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import P3
    P3.vp_start_gui()
